name: 'local-run'
on:
  workflow_dispatch: {}

jobs:
  localrun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./
        with:
          registryHost: 111111111111.dkr.ecr.ap-southeast-2.amazonaws.com
          ecrRepository: true
          roleArn: myrolearn
      - uses: ./
        with:
          registryHost: my.private.docker.repo.local
          secretsManagerSecretId: mysecretid
          secretsUsernameField: username
          secretsPasswordField: password
          roleArn: myrolearn
